name = "interactive-pipeline"
main = "worker/index.js"
compatibility_date = "2024-12-01"

[env.production]
name = "interactive-pipeline-prod"

[[durable_objects.bindings]]
name = "PIPELINE"
class_name = "PipelineDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["PipelineDurableObject"]

[[kv_namespaces]]
binding = "PIPELINE_KV"
id = "02880991d75f437b8e841ee37808087e"

[[d1_databases]]
binding = "DB"
database_name = "pipeline_db"
database_id = "dd560f98-284f-4f09-99e2-cee23e6949a5"
